### ISSUE TITLE
Can not install angularutils:pagination in meteor

### ISSUE THREAD

**Issue by hpham33** [michaelbromley/angularUtils-pagination#8] opened 2015-10-20 13:48 UTC
When I run the command
```
meteor add angularutils:pagination
```
got the following error
```
 => Errors while adding packages:

While checking for angularutils:pagination@0.9.1:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.
```
Please help to resolve this. Thanks

**Comment by michaelbromley** [comment] 2015-10-20 21:54
Thanks for the report, this is a duplicate of https://github.com/michaelbromley/angularUtils/issues/247 in the main repo. Check that more more updates.

**Closed by michaelbromley** 2015-10-20 21:54 UTC
